"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api, post } from "../../lib/client/api";
import type { SessionUser, TableSummary } from "../../packages/contracts/src";
import { CasinoNav } from "../ui/CasinoNav";

type SessionPayload = { user: SessionUser; csrfToken: string };

export function LobbyClient() {
  const router=useRouter();const[user,setUser]=useState<SessionUser|null>(null);const[tables,setTables]=useState<TableSummary[]>([]);const[loading,setLoading]=useState(true);const[creating,setCreating]=useState(false);const[joining,setJoining]=useState(false);const[error,setError]=useState("");
  const load=useCallback(async()=>{try{const session=await api<SessionPayload|null>("auth/session");if(!session){router.replace("/");return}setUser(session.user);setTables(await api<TableSummary[]>("tables"));}catch(reason){setError(reason instanceof Error?reason.message:"The lobby could not be loaded")}finally{setLoading(false)}},[router]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);try{const result=await post<{tableId:string}>("tables",{name:form.get("name"),maxSeats:Number(form.get("maxSeats")),minBet:Number(form.get("minBet")),maxBet:Number(form.get("maxBet")),deckCount:Number(form.get("deckCount")),blackjackPayout:1.5,dealerHitsSoft17:false,allowSurrender:true,visibility:"private"});await post(`tables/${result.tableId}/seat`,{seatNumber:4});router.push(`/table/${result.tableId}`)}catch(reason){setError(reason instanceof Error?reason.message:"Table creation failed")}}
  async function join(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const code=String(new FormData(event.currentTarget).get("code")??"").trim().toUpperCase();try{const result=await post<{tableId:string}>("tables/join",{code});router.push(`/table/${result.tableId}`)}catch(reason){setError(reason instanceof Error?reason.message:"Invite could not be used")}}
  if(loading||!user)return <main className="loading-screen"><span className="brand-loader">LOW STAKES</span><p>Opening the lobby…</p></main>;
  return <main className="lobby-screen"><CasinoNav user={user}/><div className="lobby-content">
    <section className="lobby-hero"><div><span className="overline">PRIVATE CASINO</span><h1>The table is yours.</h1><p>Create a room, send the code, and make a series of completely defensible decisions.</p></div><div className="lobby-actions"><button className="cream-button" onClick={()=>setCreating(true)}>Create a table</button><button className="outline-button" onClick={()=>setJoining(true)}>Join with code</button></div></section>
    <section className="table-list-section"><div className="section-heading"><div><span className="overline">YOUR TABLES</span><h2>Pull up a chair</h2></div><button className="icon-refresh" onClick={()=>void load()} aria-label="Refresh tables">↻</button></div>
      {tables.length===0?<div className="honest-empty"><span className="empty-table-art"><i/><i/><i/></span><h3>No tables are waiting.</h3><p>Create one and invite friends from Discord. We refuse to invent people to make this screen look busier.</p><button className="text-button" onClick={()=>setCreating(true)}>Create the first table</button></div>:<div className="table-grid">{tables.map(table=><article className="lobby-table-card" key={table.id}><div className="table-card-top"><span className={`table-state state-${table.status}`}>{table.status==="in_round"?"ROUND IN PLAY":"OPEN"}</span><span>{table.gameType.toUpperCase()}</span></div><h3>{table.name}</h3><p>Hosted by {table.ownerDisplayName}</p><div className="table-card-stats"><span><b>{table.seatedCount}/{table.maxSeats}</b>seated</span><span><b>{table.spectatorCount}</b>watching</span><span><b>${table.minBet}–${table.maxBet}</b>limits</span></div><button onClick={()=>router.push(`/table/${table.id}`)}>{table.status==="in_round"?"Rejoin table":"Enter table"}<span>→</span></button></article>)}</div>}
    </section>
    <footer className="lobby-footer"><span>Virtual currency only. No purchases, transfers, prizes, or cash value.</span><nav><a href="/rules">Rules</a><a href="/legal">Legal</a><a href="/settings">Settings</a></nav></footer>
  </div>
  {(creating||joining)&&<div className="modal-scrim" onMouseDown={(event)=>{if(event.currentTarget===event.target){setCreating(false);setJoining(false)}}}><section className="casino-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>{setCreating(false);setJoining(false)}} aria-label="Close">×</button>{creating?<form onSubmit={create}><span className="overline">NEW PRIVATE TABLE</span><h2>Set the felt.</h2><p>Rules can be adjusted between rounds. The dealer stays automated in this release.</p><label>Table name<input name="name" required minLength={2} maxLength={40} defaultValue={`${user.displayName}'s table`}/></label><div className="form-grid"><label>Seats<select name="maxSeats" defaultValue="7"><option>3</option><option>5</option><option>7</option></select></label><label>Decks<select name="deckCount" defaultValue="6"><option>1</option><option>2</option><option>4</option><option>6</option><option>8</option></select></label><label>Minimum bet<input name="minBet" type="number" min="1" defaultValue="25"/></label><label>Maximum bet<input name="maxBet" type="number" min="1" defaultValue="500"/></label></div><button className="cream-button" type="submit">Create private table</button></form>:<form onSubmit={join}><span className="overline">JOIN A TABLE</span><h2>Enter the code.</h2><p>Table codes contain six letters or numbers and arrive from someone you presumably trust.</p><label>Invite code<input className="code-input" name="code" autoComplete="off" required minLength={4} maxLength={20} placeholder="HX9K2Q"/></label><button className="cream-button" type="submit">Find the table</button></form>}{error&&<p className="form-error" role="alert">{error}</p>}</section></div>}
  </main>;
}
