"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { api, post } from "../../lib/client/api";
import { playSound } from "../../lib/client/sound";
import type { SessionUser } from "../../packages/contracts/src";
import type { BlackjackActionType, BlackjackHand, BlackjackPlayer, Card, PublicBlackjackState } from "../../packages/game-core/src";
import { CardBack, PlayingCard } from "../cards/PlayingCard";
import { CasinoNav } from "../ui/CasinoNav";
import { Initials } from "../ui/Brand";
import { DealerNpc, type DealerPose } from "./DealerNpc";
import "./dealer.css";

type Person = { userId:string;role:string;connectionStatus:string;ready:boolean;pendingBet:number|null;displayName:string;avatarUrl:string|null;balance:number;seatNumber:number|null };
type Bundle = {
  table:{id:string;name:string;gameType:string;status:string;visibility:string;dealerMode:string;maxSeats:number;minBet:number;maxBet:number;rules:Record<string,unknown>;stateVersion:number;ownerUserId:string};
  membership:Record<string,unknown>;people:Person[];publicState:PublicBlackjackState|null;privateState:{allowedActions:BlackjackActionType[];actionDeadlineAt:string|null;player:BlackjackPlayer|null}|null;chat:Array<{id:string;kind:string;body:string;created_at:string;user_id:string;display_name:string}>;serverTime:string;
};

type Preferences={sound:boolean;effectsVolume:number;notificationVolume:number;shake:boolean;reducedMotion:boolean};
const defaultPreferences:Preferences={sound:false,effectsVolume:.65,notificationVolume:.6,shake:true,reducedMotion:false};
const seatOrder=[1,2,3,4,5,6,7];

function isCard(card: Card|{id:string;hidden:true}):card is Card{return !("hidden" in card)}

function CardHand({cards,className=""}:{cards:Array<Card|{id:string;hidden:true}>;className?:string}){return <div className={`table-card-hand ${className}`}>{cards.map((card,index)=>isCard(card)?<PlayingCard compact key={card.id} rank={card.rank} suit={card.suit} className="card-enter" style={{animationDelay:`${index*70}ms`,zIndex:index}}/>:<CardBack compact key={card.id} style={{zIndex:index}}/>)}</div>}

function handTotal(hand:BlackjackHand){let total=hand.cards.reduce((sum,card)=>sum+(card.rank==="A"?11:["K","Q","J"].includes(card.rank)?10:Number(card.rank)),0);let aces=hand.cards.filter(card=>card.rank==="A").length;while(total>21&&aces){total-=10;aces--}return total}

export function BlackjackTable({tableId}:{tableId:string}){
  const router=useRouter();const[user,setUser]=useState<SessionUser|null>(null);const[data,setData]=useState<Bundle|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[bet,setBet]=useState(100);const[invite,setInvite]=useState<string|null>(null);const[chatOpen,setChatOpen]=useState(false);const[talk,setTalk]=useState("");const[seconds,setSeconds]=useState<number|null>(null);const[resultFx,setResultFx]=useState<{id:string;amount:number;kind:"win"|"loss"|"push"}|null>(null);const[shake,setShake]=useState("");const[prefs,setPrefs]=useState<Preferences>(defaultPreferences);const previousPhase=useRef<string|null>(null);const lastRound=useRef<string|null>(null);
  const load=useCallback(async(silent=false)=>{try{const [session,bundle]=await Promise.all([api<{user:SessionUser}|null>("auth/session"),api<Bundle>(`tables/${tableId}`)]);if(!session){router.replace("/");return}setUser(session.user);setData(bundle);if(!silent)setBet(current=>Math.max(bundle.table.minBet,Math.min(bundle.table.maxBet,current)))}catch(reason){if(!silent)setError(reason instanceof Error?reason.message:"The table could not be loaded")}},[router,tableId]);
  useEffect(()=>{try{const stored=localStorage.getItem("ls_preferences");if(stored)setPrefs({...defaultPreferences,...JSON.parse(stored)})}catch{}void load();},[load]);
  useEffect(()=>{const interval=setInterval(()=>void load(true),2500);return()=>clearInterval(interval)},[load]);
  useEffect(()=>{if(!data)return;const source=new EventSource(`/api/v1/tables/${tableId}/stream?since=${data.table.stateVersion}`);const refresh=()=>void load(true);source.addEventListener("table-event",refresh);source.addEventListener("heartbeat",refresh);return()=>source.close()},[data?.table.stateVersion,load,tableId]);
  useEffect(()=>{const deadline=data?.privateState?.actionDeadlineAt;if(!deadline){setSeconds(null);return}const tick=()=>setSeconds(Math.max(0,Math.ceil((new Date(deadline).getTime()-Date.now())/1000)));tick();const interval=setInterval(tick,250);return()=>clearInterval(interval)},[data?.privateState?.actionDeadlineAt]);
  useEffect(()=>{const state=data?.publicState;if(!state||!user)return;const phase=state.phase;if(phase==="settled"&&previousPhase.current!=="settled"&&lastRound.current!==state.roundId){lastRound.current=state.roundId;const player=state.players.find(item=>item.userId===user.id);const amount=player?.hands.reduce((sum,hand)=>sum+(hand.resultAmount??0),0)??0;const kind=amount>0?"win":amount<0?"loss":"push";setResultFx({id:crypto.randomUUID(),amount,kind});if(kind==="loss"&&prefs.shake&&!prefs.reducedMotion){setShake(Math.abs(amount)>=data.table.maxBet?"shake-heavy":"shake-light");setTimeout(()=>setShake(""),760)}void playSound(kind==="win"?(player?.hands.some(hand=>hand.cards.length===2&&hand.cards.some(card=>card.rank==="A"))?"blackjack":"win"):kind==="loss"?"loss":"notice",prefs.sound,prefs.effectsVolume);setTimeout(()=>setResultFx(null),2400)}previousPhase.current=phase},[data,prefs,user]);
  const act=async(path:string,body:unknown,sound:"button"|"chip"|"deal"="button")=>{setBusy(true);setError("");void playSound(sound,prefs.sound,prefs.effectsVolume);try{await post(path,body);await load(true)}catch(reason){setError(reason instanceof Error?reason.message:"That action did not reach the table")}finally{setBusy(false)}};
  const takeSeat=(seatNumber:number)=>act(`tables/${tableId}/seat`,{seatNumber});
  const place=async(amount:number)=>{setBet(amount);await act(`tables/${tableId}/bet`,{amount},"chip")};
  const gameAction=(type:BlackjackActionType)=>act(`tables/${tableId}/action`,{action:{type},expectedVersion:data?.table.stateVersion});
  const createInvite=async()=>{setBusy(true);try{const created=await post<{code:string;joinUrl:string}>(`tables/${tableId}/invites`,{});setInvite(created.code);await navigator.clipboard?.writeText(`${location.origin}${created.joinUrl}`)}catch(reason){setError(reason instanceof Error?reason.message:"Invite could not be created")}finally{setBusy(false)}};
  const sendChat=async(event:FormEvent)=>{event.preventDefault();if(!talk.trim())return;const body=talk;setTalk("");await act(`tables/${tableId}/chat`,{kind:"message",body})};
  const react=(body:string)=>act(`tables/${tableId}/chat`,{kind:"reaction",body});
  if(!data||!user)return <main className="loading-screen"><span className="brand-loader">LOW STAKES</span><p>{error||"Finding your chair…"}</p></main>;

  const me=data.people.find(person=>person.userId===user.id);const activePlayer=data.publicState?.phase==="player_turns"||data.publicState?.phase==="insurance"?data.publicState.players[data.publicState.currentPlayerIndex]:null;const myRound=data.publicState?.players.find(player=>player.userId===user.id);const allowed=data.privateState?.allowedActions??[];const dealerCards=data.publicState?.dealer.cards??[];const dealerTotal=data.publicState&&data.publicState.dealer.holeRevealed?handTotal({cards:data.publicState.dealer.cards.filter(isCard)} as BlackjackHand):dealerCards.filter(isCard).reduce((sum,card)=>sum+(card.rank==="A"?11:["K","Q","J"].includes(card.rank)?10:Number(card.rank)),0);const chips=[data.table.minBet,50,100,250,data.table.maxBet].filter((value,index,array)=>value>=data.table.minBet&&value<=data.table.maxBet&&array.indexOf(value)===index).sort((a,b)=>a-b);
  let dealerPose:DealerPose="idle";if(data.publicState?.phase==="dealer_turn")dealerPose="reveal";else if(activePlayer?.userId===user.id&&seconds!==null&&seconds<8)dealerPose="waiting";else if(data.publicState?.phase==="settled"){const net=myRound?.hands.reduce((sum,hand)=>sum+(hand.resultAmount??0),0)??0;dealerPose=net>0?"player-win":"house-win"}else if(data.publicState?.phase==="player_turns")dealerPose="dealing";
  const dealerLine=data.publicState?.phase==="insurance"?"Insurance is available. A side bet, not a rescue plan.":data.publicState?.phase==="dealer_turn"?"Let us see what was hiding in plain sight.":seconds!==null&&seconds<8?"The cards remain patient. Barely.":data.publicState?.phase==="settled"?"The arithmetic has spoken.":"The table is listening.";

  return <main className="blackjack-screen"><CasinoNav user={{...user,balance:me?.balance??user.balance}} tableName={data.table.name} inviteCode={invite}/><section className={`game-presentation ${shake}`} aria-label="Blackjack table">
    <div className="table-ambient-light"/><div className="npc-anchor"><DealerNpc pose={dealerPose}/><div className="dealer-nameplate"><span>THE HOUSE</span><p>{dealerLine}</p></div></div>
    <div className="shoe-prop" aria-label={`${data.publicState?.shoe.remaining??0} cards remain in the shoe`}><span/><CardBack compact/><i>{data.publicState?Math.round(data.publicState.shoe.remaining/data.publicState.shoe.initialSize*100):100}%</i></div>
    <div className="iso-table-depth"/><div className="iso-table"><div className="felt-lines"/><div className="felt-title"><span>BLACKJACK PAYS 3 TO 2</span><b>LOW STAKES</b><small>Dealer {data.table.rules.dealerHitsSoft17?"hits":"stands"} on soft 17</small></div></div>
    <div className="dealer-cards-zone">{dealerCards.length?<CardHand cards={dealerCards}/>:<div className="waiting-cards"><CardBack compact/><CardBack compact/></div>}{dealerCards.length>0&&<span className="total-chip">{dealerTotal}</span>}</div>
    <div className="seat-layer">{seatOrder.slice(0,data.table.maxSeats).map(seatNumber=>{const person=data.people.find(item=>item.seatNumber===seatNumber);const roundPlayer=data.publicState?.players.find(item=>item.seat===seatNumber);const isMe=person?.userId===user.id;const isTurn=activePlayer?.seat===seatNumber;return <div className={`iso-seat seat-${seatNumber} ${isTurn?"is-turn":""} ${isMe?"is-me":""} ${!person?"is-free":""}`} key={seatNumber}>
      {roundPlayer&&<div className="seat-hands">{roundPlayer.hands.map((hand,index)=><div className="seat-hand" key={hand.id}><CardHand cards={hand.cards}/><span className={`total-chip status-${hand.status}`}>{handTotal(hand)}</span>{roundPlayer.hands.length>1&&<small>HAND {index+1}</small>}</div>)}</div>}
      <button className="seat-portrait" disabled={Boolean(person)||busy||data.table.status==="in_round"} onClick={()=>takeSeat(seatNumber)} aria-label={person?`${person.displayName}, ${person.connectionStatus}${isTurn?", taking their turn":""}`:`Take seat ${seatNumber}`}>
        {person?<>{person.avatarUrl?<img src={person.avatarUrl} alt=""/>:<Initials name={person.displayName}/>}<i className={`connection-dot ${person.connectionStatus}`}/></>:<span className="seat-plus">+</span>}
      </button>
      {person?<div className="seat-plate"><b>{isMe?"You":person.displayName}</b><span>${person.balance.toLocaleString()}</span>{person.pendingBet&&<small>BET ${person.pendingBet}</small>}{person.ready&&<em>READY</em>}</div>:<span className="free-seat-copy">TAKE SEAT</span>}
      {isTurn&&<div className="turn-crown">YOUR TURN</div>}{isMe&&resultFx&&<div key={resultFx.id} className={`money-impact ${resultFx.kind}`}>{resultFx.kind==="win"?"+":resultFx.kind==="loss"?"−":""}${Math.abs(resultFx.amount).toLocaleString()}<small>{resultFx.kind.toUpperCase()}</small></div>}
    </div>})}</div>
    <div className="table-toolbar"><button onClick={()=>void createInvite()} disabled={busy}>Invite friends</button><span>{data.people.filter(person=>person.seatNumber!==null).length}/{data.table.maxSeats} seated</span><button onClick={()=>setChatOpen(value=>!value)}>Table talk <i>{data.chat.length}</i></button><button onClick={()=>router.push("/settings")}>Settings</button></div>
    <div className="action-rail" aria-live="polite">
      {!me?.seatNumber?<div className="action-message"><span>WATCHING</span><b>Choose an open seat between rounds.</b></div>:data.table.status!=="in_round"?<><div className="bet-readout"><span>YOUR BET</span><b>${bet}</b></div><div className="rail-chips">{chips.map(value=><button key={value} className={me.pendingBet===value?"selected":""} disabled={busy} onClick={()=>void place(value)}><span>${value}</span></button>)}</div><button className="ready-button" disabled={busy||!me.pendingBet} onClick={()=>act(`tables/${tableId}/ready`,{ready:!me.ready},"deal")}>{me.ready?"Not ready":"Ready up"}<small>{me.pendingBet?`Bet locked at $${me.pendingBet}`:"Place a bet first"}</small></button></>:allowed.length?<><div className="action-message"><span>{data.publicState?.phase==="insurance"?"DEALER SHOWS AN ACE":"YOUR DECISION"}</span><b>{data.publicState?.phase==="insurance"?"Insurance pays 2 to 1":"Choose the next move"}</b></div><div className="game-actions">{allowed.map(action=><button key={action} disabled={busy} className={action==="stand"?"primary":""} onClick={()=>void gameAction(action)}><span>{action==="decline_insurance"?"NO THANKS":action.replace("_"," ").toUpperCase()}</span><small>{action==="hit"?"Draw one":action==="stand"?"Keep this hand":action==="double"?"Double and draw":action==="split"?"Play two hands":action==="surrender"?"Recover half":"Side bet"}</small></button>)}</div>{seconds!==null&&<div className={`rail-timer ${seconds<8?"urgent":""}`}><svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="20"/><circle className="timer-line" cx="24" cy="24" r="20" style={{strokeDashoffset:126-(126*Math.min(seconds,Number(data.table.rules.turnSeconds??25))/Number(data.table.rules.turnSeconds??25))}}/></svg><b>{seconds}</b></div>}</>:<div className="action-message wide"><span>{data.publicState?.phase==="settled"?"ROUND COMPLETE":data.table.status==="in_round"?"TABLE IN PLAY":"BETTING OPEN"}</span><b>{data.publicState?.phase==="settled"?"Place a new bet when you are ready.":activePlayer?`${activePlayer.displayName} is deciding.`:"Waiting for seated players."}</b></div>}
    </div>
    {chatOpen&&<aside className="table-talk-panel"><header><div><span>TABLE TALK</span><b>Keep it civil. Keep it brief.</b></div><button onClick={()=>setChatOpen(false)} aria-label="Close table talk">×</button></header><div className="talk-messages">{data.chat.length?data.chat.map(message=><article className={message.kind==="reaction"?"reaction-message":""} key={message.id}><span className="talk-avatar"><Initials name={message.display_name}/></span><div><b>{message.user_id===user.id?"You":message.display_name}</b><p>{message.body}</p></div></article>):<p className="chat-empty">No one has said anything regrettable yet.</p>}</div><div className="reaction-row">{["BRAVE","PAINFUL","CLEAN","AGAIN"].map(item=><button key={item} onClick={()=>void react(item)}>{item}</button>)}</div><form onSubmit={sendChat}><input value={talk} maxLength={180} onChange={event=>setTalk(event.target.value)} placeholder="Say something measured…" aria-label="Table chat message"/><button>SEND</button></form></aside>}
    {error&&<div className="table-error" role="alert"><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}
    <div className="sr-status" role="status" aria-live="polite">{activePlayer?`${activePlayer.displayName}'s turn.`:""}{resultFx?` Your result is ${resultFx.kind}, ${resultFx.amount} play dollars.`:""}</div>
  </section><footer className="table-legal"><span>Play money only. No purchases, prizes, transfers, or cash value.</span><button onClick={()=>act(`tables/${tableId}/leave`,{}).then(()=>router.push("/lobby"))}>Leave table</button></footer></main>
}
